image:
  name:    "madlad-custom"

build:
  mg5:     "2.9.26" # MG5 version, (or path to a local installation)
  pythia:  "8.313"
  lhapdf:  "6.5.5"
  fastjet: "3.4.0"
  delphes: "3.5.0"

extra:
  pdfs:   [247000, 260000, 260400, 303400, 315000, 325100]  # Additional pdf sets
  models: ["2HDMtII_NLO", "HC_NLO_X0_UFO", "loop_qcd_qed_sm_Gmu"]  # Additional models
